### ISSUE TITLE
Verbesserungen

### ISSUE THREAD

**Issue by zeldafan00001** [kallioderso/Phexor#2]
- Timer durch Klicken ersetzen.
- „Zurück“-Button hinzufügen.
- Seitennavigation mit Scrollfunktion versehen.
- Dateiinformationen hinzufügen.

**Comment by kallioderso** [comment]
Vielen Dank für ihr Feedback, wir würden verschiedene Ansätze der Behebung der Probleme bzw. Hinzufügung von Funktionen erstellen, und diese ihnen Später (1 bis 2 Wochen) vorstellen damit sie die ihnen am besten gefallenste version auswählen können

Liebe Grüße, _kallioderso_

**Comment by kallioderso** [comment]
Das Tutorial wurde soeben im neusten Commit entfernt, da es zu sehr in Richtung Design ging und eher wenig zum eigentlichen Projektziel Beitrug, stattdessen werden mit jeder Neuen Großen Release Version Tutorial Videos kommen, wir bitten um ihr Verständnis für diesen fall
